# Minimal test configuration
data:
  train_path: "/scratch/vchaurasia/fastmri_data/train"  # Use full training data
  val_path: "/scratch/vchaurasia/fastmri_data/val"      # Use validation data
  test_path: "/scratch/vchaurasia/fastmri_data/test"
  acceleration: 4
  center_fraction: 0.08
  num_workers: 4        # More workers for cluster
  batch_size: 2         # Larger batch size
  mask_type: "random"

model:
  name: "disco_neural_operator"
  in_channels: 2
  out_channels: 2
  hidden_channels: 64   # Larger model for full training
  num_layers: 4         # More layers
  modes: 12             # More Fourier modes
  width: 64
  dropout: 0.1
  use_residual: true
  activation: "gelu"

training:
  epochs: 100           # Full training
  learning_rate: 0.0001
  weight_decay: 0.000001
  scheduler: "cosine"
  warmup_epochs: 5
  gradient_clip: 1.0
  mixed_precision: true 
  save_every: 10
  validate_every: 1
 
loss:
  type: "combined"
  l1_weight: 1.0
  ssim_weight: 0.1
  perceptual_weight: 0.0  # Disable for speed
  data_consistency_weight: 0.5

optimizer:
  name: "adamw"
  betas: [0.9, 0.999]
  eps: 1.0e-8
  amsgrad: false

evaluation:
  metrics: ["psnr", "ssim", "nmse"]
  save_images: true
  num_test_images: 5

system:
  device: "cuda"
  seed: 42
  num_threads: 8
  log_level: "INFO"

logging:
  use_wandb: false
  project_name: "test_mri_reconstruction"
  log_dir: "/home/vchaurasia/projects/mri_fno/outputs/test_logs"
  save_model_dir: "/home/vchaurasia/projects/mri_fno/outputs/test_models"
  results_dir: "/home/vchaurasia/projects/mri_fno/outputs/test_results"