# Quick test config
data:
  train_path: "/scratch/vchaurasia/fastmri_data/train"
  val_path: "/scratch/vchaurasia/fastmri_data/val"
  test_path: "data/quick_test"
  acceleration: 4
  center_fraction: 0.08
  num_workers: 0
  batch_size: 1
  mask_type: "random"

model:
  name: "disco_neural_operator"
  in_channels: 2
  out_channels: 2
  hidden_channels: 64
  num_layers: 4
  modes: 12
  width: 64
  dropout: 0.1
  use_residual: true
  activation: "gelu"

# Add the missing loss section
loss:
  type: "combined"
  l1_weight: 1.0
  ssim_weight: 0.1
  perceptual_weight: 0.01
  data_consistency_weight: 1.0

# Add other required sections
optimizer:
  name: "adamw"
  betas: [0.9, 0.999]
  eps: 0.00000001
  amsgrad: false

training:
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.000001
  scheduler: "cosine"

evaluation:
  metrics: ["psnr", "ssim", "nmse"]
  save_images: true
  num_test_images: 50

system:
  device: "cuda"
  seed: 42
  num_threads: 8
  log_level: "INFO"

logging:
  use_wandb: false
  project_name: "mri_reconstruction"
  log_dir: "logs"
  save_model_dir: "outputs/models"
  results_dir: "outputs/results"
