# File: configs/unet_inference_scratch_fixed.yaml
# Fixed UNet config to match training parameters

# Data Configuration
data:
  train_path: "/scratch/vchaurasia/fastmri_data/train"
  val_path: "/scratch/vchaurasia/fastmri_data/val"
  test_path: "/scratch/vchaurasia/fastmri_data/test"
  acceleration: 4
  center_fraction: 0.08
  num_workers: 4
  batch_size: 1
  mask_type: "random"

# Model Configuration - FIXED to match training
model:
  name: "unet_cnn"
  in_channels: 2
  out_channels: 2
  features: 64        # This was the issue! Training used 'features', not 'hidden_channels'
  depth: 4
  dropout: 0.1
  use_residual: false
  activation: "relu"

# Loss Configuration (needed for model loading)
loss:
  type: "combined"
  l1_weight: 1.0
  ssim_weight: 0.1
  perceptual_weight: 0.0
  data_consistency_weight: 0.5

# Evaluation Configuration
evaluation:
  metrics: ["psnr", "ssim", "nmse", "mae", "nrmse"]
  save_images: true
  save_raw_data: true
  num_test_images: 10

# System Configuration
system:
  device: "cuda"
  seed: 42
  num_threads: 8
  log_level: "INFO"

# Logging - scratch only
logging:
  use_wandb: false
  project_name: "unet_inference"
  log_dir: "/scratch/vchaurasia/organized_models/inference_logs"
  save_model_dir: "/scratch/vchaurasia/organized_models"
  results_dir: "/scratch/vchaurasia/organized_models/inference_results"