# File: configs/unet_baseline_config.yaml

# Data Configuration - same as DISCO
data:
  train_path: "/scratch/vchaurasia/fastmri_data/train"
  val_path: "/scratch/vchaurasia/fastmri_data/val"
  test_path: "/scratch/vchaurasia/fastmri_data/test"
  acceleration: 4
  center_fraction: 0.08
  num_workers: 4
  batch_size: 2  # Slightly larger for faster training
  mask_type: "random"
  
# Model Configuration - Traditional U-Net
model:
  name: "unet_cnn"
  in_channels: 2
  out_channels: 2
  features: 64        # Base number of features
  depth: 4           # U-Net depth
  dropout: 0.1
  use_residual: false
  activation: "relu"

# Training Configuration - Faster training
training:
  epochs: 30         # Fewer epochs for quick comparison
  learning_rate: 0.0001
  weight_decay: 0.000001
  scheduler: "cosine"
  warmup_epochs: 5
  gradient_clip: 1.0
  mixed_precision: true 
  save_every: 10
  validate_every: 1
 
  scheduler: "cosine"
  warmup_epochs: 2
  gradient_clip: 1.0
  mixed_precision: true
  save_every: 5
  validate_every: 1
 
# Loss Configuration - Same as DISCO
loss:
  type: "combined"
  l1_weight: 1.0
  ssim_weight: 0.1
  perceptual_weight: 0.0
  data_consistency_weight: 0.5

# Optimization
optimizer:
  name: "adam"      # Adam instead of AdamW for faster training
  betas: [0.9, 0.999]
  eps: 0.00000001
  amsgrad: false

# Evaluation
evaluation:
  metrics: ["psnr", "ssim", "nmse"]
  save_images: true
  num_test_images: 5

# System Configuration
system:
  device: "cuda"
  seed: 42
  num_threads: 8
  log_level: "INFO"

# Logging
logging:
  use_wandb: false
  project_name: "unet_baseline"
  log_dir: "/home/vchaurasia/projects/mri_fno/outputs/unet_logs"
  save_model_dir: "/home/vchaurasia/projects/mri_fno/outputs/unet_models"
  results_dir: "/home/vchaurasia/projects/mri_fno/outputs/unet_results"